#!/usr/bin/env python 
# coding: utf-8  
# In[16]:   
import numpy as np  
import pandas as pd #for Importing Data 
import matplotlib.pyplot as plt #for plotting 
import seaborn as sns #for plotting 
from ttictoc import tic,toc 
from random import randrange 
import random 
from math import sqrt 
from math import e  
dt = pd.read_csv('heart.csv') #Edit accordingly 
dt.columns  =  ['Age',  'Sex',  'Chest_pain_type',  'Resting_blood_pressure',  'Cholesterol', 
'Fasting_blood_sugar', 'Rest_ecg', 'Max_heart_rate_achieved',        'Exercise_induced_angina',  'St_depression',  'St_slope',  'Num_major_vessels',  'Thalassemia', 
'Target'] 
dt.head()#For cheking   
# In[3]:   
dt.dtypes #As we can see some attributes must be of categorical value. However they are represented 
as integers. 
#We will create dummy variables for categorical variables later.    
# In[3]:
dt.describe() #Checking Properties of the Data   
# In[4]:   
dt.Target.value_counts() #it shows the number of patients who has heart disease and patients who 
doesn't have heart disease   
# In[5]:    
# plot histograms for each variable 
dt.hist(figsize = (12, 12)) 
plt.show()   
# In[6]:   
#Produce Correlation Matrix to see how each attribution affects each other 
plt.figure(figsize=(15,15)) 
sns.heatmap(dt.corr(),annot=True, linewidths=0.5, fmt='.2f', cmap="coolwarm") 
plt.show() 
#It can be seen that attributes are not linearly independent of each other.    
# In[17]:   
#Now we need to create dummy variables for categorical variables. 
#We need to first decide on which attributes are the categorical variables 
categorical_val = [] 
noncategorical_val = [] 
for column in dt.columns:     if len(dt[column].unique()) <= 5:  #Educated Guess 
    categorical_val.append(column)     else:         noncategorical_val.append(column)          
print("Categorical Values:")         
print(categorical_val) 
print(f" Total Number : {len(categorical_val)}") 
print('<============================================================================================>') 
print("Non-Categorical Values:")         
print(noncategorical_val) 
print(f" Total Number : {len(noncategorical_val)}")   
# In[8]:   
#So, there are 9 categorical variables and 5 continuous variables. While continuous variables is already 
quantified,  
#we have to quantify categorical variables as well. This is done by dummy coding. 
#But firstly, lets see how continuous variables are related to target. 
import plotly.express as px #For 3d data plot 
fig = px.scatter_3d(dt, x='Cholesterol', y='Max_heart_rate_achieved', z='Age', size='St_depression',               color='Target',opacity=1) 
fig.show() 
#Couldn't fit in Resting Blood Pressure   
# In[9]:
